Kutuphane/Kutuphane/Models/Entity/KITAP.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KITAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KITAP()
        {
            this.TBLHAREKET = new HashSet<TBLHAREKET>();
        }
    
        public int ID { get; set; }
        public string AD { get; set; }
        public Nullable<byte> KATEGORI { get; set; }
        public Nullable<int> YAZAR { get; set; }
        public string BASIMYIL { get; set; }
        public string YAYINEVI { get; set; }
        public string SAYFA { get; set; }
        public Nullable<bool> DURUM { get; set; }
        public string KITAPRESIM { get; set; }
    
        public virtual TBLKATEGORI TBLKATEGORI { get; set; }
        public virtual TBLYAZAR TBLYAZAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLHAREKET> TBLHAREKET { get; set; }
    }
}

Kutuphane/Kutuphane/Controllers/KitapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kutuphane.Models.Entity;

namespace Kutuphane.Controllers
{
    public class KitapController : Controller
    {
        // GET: Kitap
        DBKUTUPHANEEntities db = new DBKUTUPHANEEntities();
        public ActionResult Index(string p)
        {
            //var kitaplar = db.KITAP.ToList();
            var kitaplar = from k in db.KITAP select k;
            if (!string.IsNullOrEmpty(p))
            {
                kitaplar = kitaplar.Where(m => m.AD.Contains(p));
            }
            return View(kitaplar.ToList());
        }

        
        [HttpGet]
        public ActionResult KitapEkle()
        {
            //DopDownlist ile veri tabanından texboxa veri çekmek
            List<SelectListItem> dgr1 = (from i in db.TBLKATEGORI.ToList()
                                         select new SelectListItem
                                         {
                                             Text = i.AD,
                                             Value = i.ID.ToString()
                                         }).ToList();
            ViewBag.deger1 = dgr1;
            //////////////////////////////////////////////////////////
            List<SelectListItem> dgr2 = (from i in db.TBLYAZAR.ToList()
                                         select new SelectListItem
                                         {
                                             Text = i.AD +" "+ i.SOYAD,
                                             Value = i.ID.ToString()
                                         }).ToList();
            ViewBag.deger2 = dgr2;
            return View();
        }


        [HttpPost]
        public ActionResult KitapEkle (KITAP p)
        {
            var ktgr = db.TBLKATEGORI.Where(k => k.ID == p.TBLKATEGORI.ID).FirstOrDefault();
            var yzr = db.TBLYAZAR.Where(k => k.ID == p.TBLYAZAR.ID).FirstOrDefault();
            p.TBLKATEGORI = ktgr;
            p.TBLYAZAR = yzr;
            db.KITAP.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult KitapSil(int id)
        {
            var ktp = db.KITAP.Find(id);
            db.KITAP.Remove(ktp);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult KitapGetir(int id)
        {
            var ktp = db.KITAP.Find(id);
            List<SelectListItem> dgr1 = (from i in db.TBLKATEGORI.ToList()
                                         select new SelectListItem
                                         {
                                             Text = i.AD,
                                             Value = i.ID.ToString()
                                         }).ToList();
            ViewBag.deger1 = dgr1;
            
            List<SelectListItem> dgr2 = (from i in db.TBLYAZAR.ToList()
                                         select new SelectListItem
                                         {
                                             Text = i.AD+" "+i.SOYAD,
                                             Value = i.ID.ToString()
                                         }).ToList();
            ViewBag.deger2 = dgr2;
            return View("KitapGetir", ktp);
        }

        public ActionResult KitapGuncelle (KITAP p)
        {
            var kitap = db.KITAP.Find(p.ID);
            kitap.AD = p.AD;
            kitap.BASIMYIL = p.BASIMYIL;
            kitap.SAYFA = p.SAYFA;
            kitap.YAYINEVI = p.YAYINEVI;
            var ktg = db.TBLKATEGORI.Where(k => k.ID == p.TBLKATEGORI.ID).FirstOrDefault();
            var yzr = db.TBLYAZAR.Where(y => y.ID == p.TBLYAZAR.ID).FirstOrDefault();
            kitap.KATEGORI = ktg.ID;
            kitap.YAZAR = yzr.ID;
            kitap.DURUM = true;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        
    }
}

Kutuphane/Kutuphane/Views/Kitap/Index.cshtml
@using Kutuphane.Models.Entity
@model List<KITAP>


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Kitap Sayfası</h2>

@using (Html.BeginForm("Index", "Kitap", FormMethod.Get))
{
    <div style="margin-bottom:15px;margin-top:15px">
        <b>Aranacak Kitap Adını Buraya</b> &nbsp;
        @Html.TextBox("p")
        <input  type="submit" value="Ara" />
    </div>
}


<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>Kitap Adı </th>
        <th>Kategori </th>
        <th>Yazarı </th>
        <th>Yayın Evi </th>
        <th> Sayfa</th>
        <th> Durumu</th>
        <th>Sil</th>
        <th>Güncelle</th>


    </tr>
    @foreach (var ktp in Model)
    {
        <tr>
            <td>@ktp.ID</td>
            <td>@ktp.AD</td>
            @*ilişkili tablo yazar adı ekleme*@
            <td>@ktp.TBLKATEGORI.AD </td>
            <td>@ktp.TBLYAZAR.AD&nbsp; @ktp.TBLYAZAR.SOYAD</td>
            <td>@ktp.YAYINEVI</td>
            <td>@ktp.SAYFA</td>
            <td>@ktp.DURUM</td>
            <td> <a href="/Kitap/KitapSil/@ktp.ID/" class="btn btn-danger">Sil</a></td>
            <td> <a href="/Kitap/KitapGetir/@ktp.ID/" class="btn btn-success">Güncelle</a></td>
        </tr>
    }
</table>
<a href="/Kitap/KitapEkle/" class="btn btn-primary">Yeni Kitap Ekle</a>

Kutuphane/Kutuphane/Views/Kitap/KitapEkle.cshtml
@model Kutuphane.Models.Entity.KITAP

@{
    ViewBag.Title = "KitapEkle";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<form  method="post">
    <div style="margin-top:25px">
        <label>Kitap Adı</label>
        @Html.TextBoxFor(k => k.AD, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Kategorisi</label>
        @*/////////////////////////////////////////////////////*@
        @Html.DropDownListFor(k => k.TBLKATEGORI.ID, (List<SelectListItem>)ViewBag.deger1, new { @class = "form-control" })
        @*////////////////////////////////////////////////////////*@
    </div>
    <div style="margin-top:15px">
        <label>Kitap Yazarı</label>
        @Html.DropDownListFor(k => k.TBLYAZAR.ID, (List<SelectListItem>)ViewBag.deger2, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Basım Yılı</label>
        @Html.TextBoxFor(k => k.BASIMYIL, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Yayın Evi</label>
        @Html.TextBoxFor(k => k.YAYINEVI, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Sayfası</label>
        @Html.TextBoxFor(k => k.SAYFA, new { @class = "form-control" })
    </div>
    
    <div style="margin-top:15px">
        <button class="btn btn-info">Kitap Ekle</button>
    </div>
    <input type="hidden" name="DURUM" value="true" />
</form>

Kutuphane/Kutuphane/Views/Kitap/KitapGetir.cshtml
@model Kutuphane.Models.Entity.KITAP
@{
    ViewBag.Title = "KitapGetir";
    Layout = "~/Views/Shared/Layout.cshtml";
}

@using (Html.BeginForm("KitapGuncelle", "Kitap", FormMethod.Post))
{
    <div class="form-group">
        <label>Kitap ID</label>
        @Html.TextBoxFor(y => y.ID, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Kitap Adı</label>
        @Html.TextBoxFor(y => y.AD, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Kategori</label>
        @Html.DropDownListFor(k => k.TBLKATEGORI.ID, (List<SelectListItem>)ViewBag.deger1, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Yazar</label>
        @Html.DropDownListFor(k => k.TBLYAZAR.ID, (List<SelectListItem>)ViewBag.deger2, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Basım Yılı</label>
        @Html.TextBoxFor(y => y.BASIMYIL, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Yayın Evi</label>
        @Html.TextBoxFor(y => y.YAYINEVI, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Sayfa</label>
        @Html.TextBoxFor(y => y.SAYFA, new { @class = "form-control" })
    </div>
    
    <button class="btn btn-warning">Kitap Bilgilerini Güncelle</button>
}