Kutuphane/Kutuphane/Controllers/UyeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kutuphane.Models.Entity;
using PagedList;
using PagedList.Mvc;
namespace Kutuphane.Controllers
    
{
    public class UyeController : Controller
    {
        // GET: Uye
        DBKUTUPHANEEntities db = new DBKUTUPHANEEntities();
        public ActionResult Index( int sayfa=1)
        {
            var veri = db.TBLUYELER.ToList().ToPagedList(sayfa,4);
            return View(veri);
        }



        [HttpGet]
        public ActionResult UyeEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UyeEkle(TBLUYELER u)
        {
            if (!ModelState.IsValid)
            {
                return View("UyeEkle");
            }
            db.TBLUYELER.Add(u);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult UyeSil(int id)
        {
            var uye = db.TBLUYELER.Find(id);
            db.TBLUYELER.Remove(uye);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        public ActionResult UyeGetir(int id)
        {
            var uye = db.TBLUYELER.Find(id);
            return View("UyeGetir", uye);
        }

        public ActionResult UyeGuncelle(TBLUYELER u)
        {
            var uye = db.TBLUYELER.Find(u.ID);
            uye.AD = u.AD;
            uye.SOYAD= u.SOYAD;
            uye.MAIL= u.MAIL;
            uye.KULLANICIADI= u.KULLANICIADI;
            uye.SIFRE= u.SIFRE;
            uye.FOTOGRAF= u.FOTOGRAF;
            uye.TELEFON= u.TELEFON;
            uye.OKUL= u.OKUL;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
         public ActionResult UyeKitaplar (int id)
        {
            var uyekitap = db.TBLHAREKET.Where(x => x.UYE == id).ToList();
            var uyead = db.TBLUYELER.Find(id).AD;
            var uyesoyad = db.TBLUYELER.Find(id).SOYAD;
            ViewBag.ad = uyead;
            ViewBag.soyad = uyesoyad;
            return View(uyekitap);
        }

    }
}

Kutuphane/Kutuphane/Views/Uye/Index.cshtml
@using Kutuphane.Models.Entity
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<TBLUYELER>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Üyeler</h2>

<table class="table table-bordered">
    <tr>
        <th>Üye ID</th>
        <th>Üye Adı</th>
        <th>Üye Soyadı</th>
        <th>Okul</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Kitap Geçmiş</th>
    </tr>
    @foreach (var uye in Model)
    {
        <tr>
            <td>@uye.ID</td>
            <td>@uye.AD</td>
            <td>@uye.SOYAD</td>
            <td>@uye.OKUL</td>
            <td> <a href="/Uye/UyeSil/@uye.ID" class="btn btn-danger">Sil</a></td>
            <td> <a href="/Uye/UyeGetir/@uye.ID" class="btn btn-success">Güncelle</a></td>
            <td> <a href="/Uye/UyeKitaplar/@uye.ID" class="btn btn-success" style="background-color:cyan">Kitap Geçmiş</a></td>
        </tr>
    }
</table>
@Html.PagedListPager((IPagedList)Model,sayfa=>Url.Action("Index",new { sayfa }))
<a href="/Uye/UyeEkle/" class="btn btn-info">Yeni Üye Ekle</a>

Kutuphane/Kutuphane/Views/Uye/UyeEkle.cshtml
@model Kutuphane.Models.Entity.TBLUYELER
@{
    ViewBag.Title = "UyeEkle";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<br />
<form method="post" style="margin-left:15px" class="form-group">
    <label>Üye Adı</label>
    @Html.TextBoxFor(x => x.AD, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.AD, "", new { @Style = "color:red" })
    <br />
    <label>Soyadı</label>
    @Html.TextBoxFor(x => x.SOYAD, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.SOYAD, "", new { @Style = "color:red" })
    <br />
    <label>Mail</label>
    @Html.TextBoxFor(x => x.MAIL, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.MAIL, "", new { @Style = "color:red" })
    <br />
    <label>Kullanıcı Adı</label>
    @Html.TextBoxFor(x => x.KULLANICIADI, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.KULLANICIADI, "", new { @Style = "color:red" })
    <br />
    <label>Şifre</label>
    @Html.TextBoxFor(x => x.SIFRE, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.SIFRE, "", new { @Style = "color:red" })
    <br />
    <label>Fotograf</label>
    @Html.TextBoxFor(x => x.FOTOGRAF, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.FOTOGRAF, "", new { @Style = "color:red" })
    <br />
    <label>Telefon No</label>
    @Html.TextBoxFor(x => x.TELEFON, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.TELEFON, "", new { @Style = "color:red" })
    <br />
    <label>Okul</label>
    @Html.TextBoxFor(x => x.OKUL, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.OKUL, "", new { @Style = "color:red" })
    <br />
    <div><button class="btn btn-info" id="Btn1">Üye Ekle</button></div>

</form>

Kutuphane/Kutuphane/Views/Uye/UyeGetir.cshtml
@model Kutuphane.Models.Entity.TBLUYELER
@{
    ViewBag.Title = "UyeGetir";
    Layout = "~/Views/Shared/Layout.cshtml";
}

@using (Html.BeginForm("UyeGuncelle", "Uye", FormMethod.Post))
{
<div class="form-group">
    @Html.LabelFor(k => k.ID)
    @Html.TextBoxFor(k => k.ID, new { @class = "form-control" })
    <br />
    <label>Uye Adı</label>
    @Html.TextBoxFor(k => k.AD, new { @class = "form-control" })
    <br />
    <label>Soyadı</label>
    @Html.TextBoxFor(k => k.SOYAD, new { @class = "form-control" })
    <br />
    <label>Mail</label>
    @Html.TextBoxFor(k => k.MAIL, new { @class = "form-control" })
    <br />
    <label>Kullanıcı Adı</label>
    @Html.TextBoxFor(k => k.KULLANICIADI, new { @class = "form-control" })
    <br />
    <label>Şifre</label>
    @Html.TextBoxFor(k => k.SIFRE, new { @class = "form-control" })
    <br />
    <label>Fotograf</label>
    @Html.TextBoxFor(k => k.FOTOGRAF, new { @class = "form-control" })
    <br />
    <label>Telefon</label>
    @Html.TextBoxFor(k => k.TELEFON, new { @class = "form-control" })
    <br />
    <label>Okul</label>
    @Html.TextBoxFor(k => k.OKUL, new { @class = "form-control" })

</div>
    <div>
        <button class="btn btn-warning">Personel Güncelle</button>
    </div>
}

Kutuphane/Kutuphane/Views/Uye/UyeKitaplar.cshtml
@using Kutuphane.Models.Entity
@model List<TBLHAREKET>
@{
    ViewBag.Title = "UyeKitaplar";
    Layout = "~/Views/Shared/Layout.cshtml";
}
<br />
<h2>@ViewBag.ad @ViewBag.soyad</h2>

<table class="table table-danger">
    <tr>
        <th>İşlem ID</th>
        <th>Kitap Adı </th>
        <th>Personel </th>
        <th>Alış Tarihi </th>
        <th> Iade Tarihi</th>

    </tr>
    @foreach (var ktp in Model)
    {
        <tr>
            <td>@ktp.ID</td>
            <td>@ktp.KITAP1.AD</td>
            <td>@ktp.TBLPERSONEL.PERSONEL</td>
            <td>@Convert.ToDateTime(ktp.ALISTARIH).ToString("dd/MMM/yyyy")</td>
            <td>@Convert.ToDateTime(ktp.MUSTEGETITARIH).ToString("dd/MM/yyyy")</td>
        </tr>
    }
</table>