Kutuphane/Kutuphane/Controllers/YazarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kutuphane.Models.Entity;

namespace Kutuphane.Controllers
{
    public class YazarController : Controller
    {
        // GET: Yazar
        DBKUTUPHANEEntities db = new DBKUTUPHANEEntities();
        public ActionResult Index()
        {
            var degerler = db.TBLYAZAR.ToList();
            db.SaveChanges();
            return View(degerler);
        }


        [HttpGet]
        public ActionResult YazarEkle ()
        {
            return View();
        }

        [HttpPost]
        public ActionResult YazarEkle(TBLYAZAR p)
        {
            if (!ModelState.IsValid)
            {
                return View("YazarEkle");
            }
            db.TBLYAZAR.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult YazarSil (int id) 
        {
            var yazar = db.TBLYAZAR.Find(id);
            db.TBLYAZAR.Remove(yazar);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        public ActionResult YazarGetir (int id)
        {
            var yzr = db.TBLYAZAR.Find(id);
            return View("YazarGetir", yzr);
        }

        public ActionResult YazarGuncelle (TBLYAZAR p)
        {
            var yzr = db.TBLYAZAR.Find(p.ID);
            yzr.ID = p.ID;
            yzr.AD = p.AD;
            yzr.SOYAD = p.SOYAD;
            yzr.DETAY = p.DETAY;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult YazarKitaplar(int id)
        {
            var liste = db.KITAP.Where(x => x.YAZAR == id).ToList();
            var yazar = db.TBLYAZAR.Where(x => x.ID == id).Select(x => x.AD + " " + x.SOYAD).FirstOrDefault();
            ViewBag.soyad = yazar;
            return View(liste);

        }
    }
}

Kutuphane/Kutuphane/Views/Yazar/Index.cshtml
@using Kutuphane.Models.Entity
@model List<TBLYAZAR>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Yazarlar</h2>
<table class="table table-striped" methot="post">
    <tr style="background-color:deepskyblue">
        <th>ID</th>
        <th>ADI</th>
        <th>SOYADI</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Yazarın Kitapları</th>
    </tr>
    @foreach(var y in Model)
            {
                <tr >
                    <td>@y.ID</td>
                    <td>@y.AD</td>
                    <td>@y.SOYAD</td>
                    @*aletr kullanımı*@
                    <td>@Html.ActionLink("Sil","YazarSil", new { id=y.ID}, 
                       new { @class="btn btn-danger", onclick="return confirm('Silmek istediğinize eminmisiniz?')"})</td>
                    <td><a href="/Yazar/YazarGetir/@y.ID" class="btn btn-success">Güncelle</a></td>
                    <td><a href="/Yazar/YazarKitaplar/@y.ID" class="btn btn-info">Yazarın Kitapları</a></td>
                    
                </tr>
            }
</table>
<a href="/Yazar/YazarEkle/" class="btn btn-primary">Yeni Yazar Ekle</a>

Kutuphane/Kutuphane/Views/Yazar/YazarEkle.cshtml
@model Kutuphane.Models.Entity.TBLYAZAR
@{
    ViewBag.Title = "YazarEkle";
    Layout = "~/Views/Shared/Layout.cshtml";
}
<form  method="post">
    <div></div>
    <div style="margin-top:15px">
        <label>Yazar Adı</label>
        @Html.TextBoxFor(y=>y.AD,new { @class="form-control"})
        @Html.ValidationMessageFor(x => x.AD)
    </div>
    <div style="margin-top:15px">
        <label>Yazar Soyadı</label>
        @Html.TextBoxFor(y=>y.SOYAD,new { @class="form-control" })
        @Html.ValidationMessageFor(x=>x.SOYAD)
    </div>
    <div style="margin-top:15px">
        <label>Detayları</label>
        @Html.TextAreaFor(y => y.DETAY, new {@class="form-control"})
    </div>
    <div style="margin-top:15px">
        <button class="btn btn-info">YAZAR EKLE</button>  
    </div>
</form>

Kutuphane/Kutuphane/Views/Yazar/YazarGetir.cshtml
@model Kutuphane.Models.Entity.TBLYAZAR

@{
    ViewBag.Title = "YazarGetir";
    Layout = "~/Views/Shared/Layout.cshtml";
}
<br />
<h2>YazarGetir</h2>
<br />
   @using (Html.BeginForm("YazarGuncelle", "Yazar", FormMethod.Post))
            {
                <div class="form-group">
                    <label>Yazar ID</label>
                    @Html.TextBoxFor(y=>y.ID, new {@class="form-control"})
                </div>
                <div class="form-group">
                    <label>Yazar Adı</label>
                    @Html.TextBoxFor(y => y.AD, new {@class="form-control"})
                </div>
                <div class="form-group">
                    <label>Yazar Soyadı</label>
                    @Html.TextBoxFor(y => y.SOYAD, new {@class="form-control"})
                </div>
                <div class="form-group">
                    <label>Detaylar</label>
                    @Html.TextAreaFor(y => y.DETAY, new {@class="form-control"})
                </div>
                <button class="btn btn-warning">Yazar Bilgilerini Güncelle</button>
            }

Kutuphane/Kutuphane/Views/Yazar/YazarKitaplar.cshtml
@using Kutuphane.Models.Entity
@model List<KITAP>
@{
    ViewBag.Title = "YazarKitaplar";
    Layout = "~/Views/Shared/Layout.cshtml";
}
<br />
<h2> @ViewBag.soyad</h2>


<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>Kitap Adı </th>
        <th>Kategori </th>
        <th>Yayın Evi </th>
        <th> Sayfa</th>
        <th> Durumu</th>
        <th>Sil</th>
        <th>Güncelle</th>


    </tr>
    @foreach (var ktp in Model)
    {
        <tr>
            <td>@ktp.ID</td>
            <td>@ktp.AD</td>
            @*ilişkili tablo yazar adı ekleme*@
            <td>@ktp.TBLKATEGORI.AD </td>
            <td>@ktp.YAYINEVI</td>
            <td>@ktp.SAYFA</td>
            <td>@ktp.DURUM</td>
            <td> <a href="/Kitap/KitapSil/@ktp.ID/" class="btn btn-danger">Sil</a></td>
            <td> <a href="/Kitap/KitapGetir/@ktp.ID/" class="btn btn-success">Güncelle</a></td>
        </tr>
    }
</table>